server:
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://数据库ip:3306/security?serverTimezone=Asia/Shanghai&useAffectedRows=true&useSSL=true&characterEncoding=utf8
    password:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.zhifa.security.entity


